[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
    "@aave/core-v3/=lib/aave-v3-core/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@uniswap/v3-core/=lib/v3-core/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@solady/=lib/solady/",
    "@balancer-labs/v2-interfaces/=lib/balancer-v2-monorepo/pkg/interfaces/"
]
evm_version = "cancun"

[rpc_endpoints]
arbitrum = "${ARBITRUM_RPC_URL}"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
